//@flow
export default class Event {

  clientVer: string;
  eventType: number;
  //the client's timestamp of this event
  eventTimestamp: number;
  //a unique string generated by the client that will represent the client-side session: the primary component will pass it on to other components that sprout from it
  sessionId: string;
  partnerId: number;
  entryId: string;

  /* //the UV cookie - creates in the operational system and should be passed on ofr every event
   uniqueViewer: string;*/

  widgetId: string;
  uiconfId: number;
  //the partner's user id
  userId: number;
  //the timestamp along the video when the event happend
  currentPoint: number;
  //the duration of the video in milliseconds - will make it much faster than quering the db for each entry
  duration: number;
  /*//will be retrieved from the request of the user
   userIp:string;

   //the time in milliseconds the event took
   processDuration: number;

   //the id of the GUI control - will be used in the future to better understand what the user clicked
   controlId:string;
   */
  //true if the user ever used seek in this session
  seek: boolean;
  /*//timestamp of the new point on the timeline of the video after the user seeks
   newPoint: number;
   */
  //the referrer of the client
  referrer: string;
  //will indicate if the event is thrown for the first video in the session
  isFirstInSession: boolean;
  //kaltura application name
  applicationId: string;
  contextId: number;
  featureType: number;

  constructor(eventType: number) {
    this.eventType = eventType;
    this.isFirstInSession = false;
    this.eventTimestamp = new Date().getTime();
    this.uiconfId = 0;
  }
}
